services:
  quizify-app:
    container_name: quizify-app
    image: quizify-app:v1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3000:3000"
    restart: on-failure

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: quizify-nginx
    ports:
      - "80:80"
    depends_on:
      - quizify-app
