export type SubscriptionPlan = {
  id: number;
  name: string;
  slug: string;
  stripe_price_id: string;
  stripe_product_id: string;
  price: string;
  currency: string;
  billing_period: string;
  description: string;
  features: string[];
  max_quizzes: number | null;
  max_questions_per_quiz: number;
  max_participants: number;
  analytics_enabled: boolean;
  export_enabled: boolean;
  team_management: boolean;
  priority_support: boolean;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
};
